# Generated by Django 3.2.7 on 2021-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
